### ISSUE TITLE
FATAL: password authentication failed for user "pio"

### ISSUE THREAD

**Issue by mgcdanny** [jamesward/pio-eventserver-heroku#2]
I am getting the following error when running:

source bin/env.sh && ./sbt run

org.postgresql.util.PSQLException: FATAL: password authentication failed for user "pio"

echo $PIO_STORAGE_SOURCES_PGSQL_URL
jdbc:postgresql://localhost/pio

echo $PIO_STORAGE_SOURCES_PGSQL_USERNAME
pio

**Comment by mgcdanny** [comment]
I found the answer in the source code.  There needs to a database called pio, a user called pio, and password called pio.   Seems to works now. Thanks

from bin/env.sh

f [ -z "${DATABASE_URL}" ]; then
    export PIO_STORAGE_SOURCES_PGSQL_URL=jdbc:postgresql://localhost/pio
    export PIO_STORAGE_SOURCES_PGSQL_USERNAME=pio
    export PIO_STORAGE_SOURCES_PGSQL_PASSWORD=pio

**Comment by jamesward** [comment]
Let me know if I need to add anything to the instructions to help with this.
